name: Cron - changeTimeZone

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # Runs "At every full hour." (see https://crontab.guru)
    - cron: "0 * * * *"

jobs:
  cron-scheduleEmailReminders:
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.APP_URL && env.CRON_SECRET }}
        run: |
          curl ${{ env.APP_URL }}/api/cron/changeTimeZone \
            -X POST \
            -H 'content-type: application/json' \
            -H 'authorization: ${{ env.CRON_SECRET }}' \
            -sSf
