name: "Welcome new contributors"

on:
  issues:
    types: opened
  pull_request:
    types: opened

permissions:
  pull-requests: write
  issues: write

jobs:
  welcome-message:
    name: Welcoming New Users
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Thank you for making your first Pull Request and taking the time to improve OneHash ! ❤️🎉
          issue-message: |
            Thank you for opening your first issue, one of our team members will review it as soon as it possible. ❤️🎉
